# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-16 21:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acusados',
            fields=[
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=150, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('colectivo', models.CharField(blank=True, max_length=25, null=True)),
                ('interno_colectivo', models.CharField(blank=True, max_length=25, null=True)),
                ('sexo', models.CharField(blank=True, max_length=25, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehiculo_numero', models.IntegerField(blank=True, null=True)),
                ('tipo_reclas_1', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'acusados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hechos',
            fields=[
                ('orden', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('comisaria', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo_colision', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_hecho', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_normalizada', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_calle', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_normalizada_arcgis', models.CharField(blank=True, max_length=200, null=True)),
                ('calle1', models.CharField(blank=True, max_length=100, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('calle2', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_calle', models.IntegerField(blank=True, null=True)),
                ('codigo_cruce', models.IntegerField(blank=True, null=True)),
                ('geocodificacion', models.CharField(blank=True, max_length=300, null=True)),
                ('franja_horaria', models.IntegerField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(blank=True, null=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('cantidad_victimas', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('fh', models.DateTimeField(blank=True, null=True)),
                ('comuna', models.IntegerField(blank=True, null=True)),
                ('participantes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=100, null=True), size=None)),
                ('geom_3857', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
                ('causa', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_colision1', models.CharField(blank=True, max_length=60, null=True)),
                ('participantes_victimas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=100, null=True), default=None, size=None)),
                ('participantes_acusados', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=100, null=True), default=None, size=None)),
            ],
            options={
                'db_table': 'hechos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Victimas',
            fields=[
                ('causa', models.CharField(blank=True, max_length=50, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=150, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('colectivo', models.CharField(blank=True, max_length=25, null=True)),
                ('interno_colectivo', models.CharField(blank=True, max_length=25, null=True)),
                ('sexo', models.CharField(blank=True, max_length=25, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sumario', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_recod', models.CharField(blank=True, max_length=50, null=True)),
                ('franja_edad', models.IntegerField(blank=True, null=True)),
                ('ubic_vehicm', models.CharField(blank=True, max_length=50, null=True)),
                ('franja_edad_itf', models.IntegerField(blank=True, null=True)),
                ('vehiculo_numero', models.IntegerField(blank=True, null=True)),
                ('tipo_reclas_1', models.CharField(blank=True, max_length=100, null=True)),
                ('id_hecho', models.ForeignKey(blank=True, db_column='id_hecho', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.Hechos')),
            ],
            options={
                'db_table': 'victimas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='acusados',
            name='id_hecho',
            field=models.ForeignKey(blank=True, db_column='id_hecho', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.Hechos'),
        ),
    ]
