# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 21:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hechos',
            fields=[
                ('orden', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('comisaria', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo_colision', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_hecho', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_normalizada', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_calle', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_normalizada_arcgis', models.CharField(blank=True, max_length=200, null=True)),
                ('calle1', models.CharField(blank=True, max_length=100, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('calle2', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_calle', models.IntegerField(blank=True, null=True)),
                ('codigo_cruce', models.IntegerField(blank=True, null=True)),
                ('geocodificacion', models.CharField(blank=True, max_length=300, null=True)),
                ('franja_horaria', models.IntegerField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(blank=True, null=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('cantidad_victimas', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('fh', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hechos',
                'managed': False,
            },
        ),
    ]
