# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hechos',
            options={'managed': True},
        ),
    ]
