# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 23:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_auto_20170112_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hechos',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
