# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0004_auto_20170112_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hechos',
            options={'managed': True},
        ),
    ]
