# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0007_auto_20170227_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acusados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='victimas',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='hechos',
            name='tipo_colision1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
