# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0008_auto_20170402_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='acusados',
            name='id_hecho',
            field=models.ForeignKey(blank=True, db_column='id_hecho', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.Hechos'),
        ),
        migrations.AddField(
            model_name='victimas',
            name='id_hecho',
            field=models.ForeignKey(blank=True, db_column='id_hecho', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.Hechos'),
        ),
    ]
