# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 21:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallesGeocod',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_i', models.IntegerField(blank=True, null=True)),
                ('alt_f', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('rango', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calles_geocod',
                'managed': False,
            },
        ),
    ]
