# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 23:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170207_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='alturas_tramo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
