# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 23:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userstats_alturas_tramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='geom_tramo',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
